# -*- coding: utf-8 -*-
"""flood model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoApEaSmwTDuE7j0Fvly1TOqeY6DjCBC
"""

!pip -q install pandas numpy scikit-learn seaborn matplotlib joblib xgboost

import os, json, joblib, warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

uploaded = files.upload()
csv_file = list(uploaded.keys())[0]
print("Uploaded:", csv_file)

df = pd.read_csv(csv_file)
print(df.shape)
df.head()

df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
df = df.copy()
df.head()

print(df.columns.tolist())
print(df.shape)

target_col = "flood_occurrence_current_event"   # matches actual column name
print("Target:", target_col)
print(df[target_col].value_counts(dropna=False))

candidate_features = [
    "district", "place_name", "latitude", "longitude", "elevation_m", "distance_to_river_m",
    "landcover", "soil_type", "water_supply", "electricity", "road_quality",
    "population_density_per_km2", "built_up_percent", "urban_rural", "rainfall_7d_mm",
    "monthly_rainfall_mm", "drainage_index", "ndvi", "ndwi", "water_presence_flag",
    "historical_flood_count", "infrastructure_score", "nearest_hospital_km",
    "nearest_evac_km"
    # excluded: flood_risk_score, inundation_area_sqm, is_good_to_live,
    # reason_not_good_to_live — these leak the target
]
features = [c for c in candidate_features if c in df.columns]
print("Using features:", features)
print("Missing/dropped:", [c for c in candidate_features if c not in df.columns])

data = df[features + [target_col]].copy()
data = data.dropna(subset=[target_col])

X = data[features].copy()
y = data[target_col].copy()

print(X.shape, y.shape)

if y.dtype == "object":
    y = y.astype(str).str.strip().str.lower()
    print(y.value_counts())

y_encoder = LabelEncoder()
y_encoded = y_encoder.fit_transform(y.astype(str))
print("Target classes:", list(y_encoder.classes_))

cat_cols = X.select_dtypes(include=["object"]).columns.tolist()
num_cols = X.columns.difference(cat_cols).tolist()

print("Numeric:", num_cols)
print("Categorical:", cat_cols)

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X_num = pd.DataFrame(num_imputer.fit_transform(X[num_cols]), columns=num_cols)
X_cat = pd.DataFrame(cat_imputer.fit_transform(X[cat_cols]), columns=cat_cols) if cat_cols else pd.DataFrame(index=X.index)

for c in cat_cols:
    X_cat[c] = X_cat[c].astype(str).str.strip().str.lower()

X_processed = pd.get_dummies(pd.concat([X_num, X_cat], axis=1), drop_first=True)
print(X_processed.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(X_train.shape, X_test.shape)

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    class_weight="balanced"
)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.9,
    colsample_bytree=0.9,
    eval_metric="logloss",
    random_state=42
)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))

rf_acc = accuracy_score(y_test, rf_pred)
xgb_acc = accuracy_score(y_test, xgb_pred)

best_model = rf if rf_acc >= xgb_acc else xgb
best_name = "RandomForest" if rf_acc >= xgb_acc else "XGBoost"
best_pred = rf_pred if rf_acc >= xgb_acc else xgb_pred

print("Best Model:", best_name)
print("Best Accuracy:", max(rf_acc, xgb_acc))

print(classification_report(y_test, best_pred, target_names=y_encoder.classes_))

cm = confusion_matrix(y_test, best_pred)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm, annot=True, fmt="d", cmap="Blues",
    xticklabels=y_encoder.classes_,
    yticklabels=y_encoder.classes_
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title(f"{best_name} Confusion Matrix")
plt.show()

importances = pd.Series(best_model.feature_importances_, index=X_processed.columns).sort_values(ascending=False)

plt.figure(figsize=(10,6))
importances.head(20).plot(kind="bar")
plt.title(f"Top 20 Feature Importances ({best_name})")
plt.ylabel("Importance")
plt.tight_layout()
plt.show()

os.makedirs("artifacts", exist_ok=True)

joblib.dump(best_model, "artifacts/flood_model.pkl")
joblib.dump(num_imputer, "artifacts/num_imputer.pkl")
joblib.dump(cat_imputer, "artifacts/cat_imputer.pkl")
joblib.dump(X_processed.columns.tolist(), "artifacts/model_columns.pkl")
joblib.dump(y_encoder, "artifacts/label_encoder.pkl")

print("Saved artifacts in /artifacts")

config = {
    "model_name": best_name,
    "accuracy": float(max(rf_acc, xgb_acc)),
    "target_classes": y_encoder.classes_.tolist(),
    "features_used": features,
    "model_columns_count": len(X_processed.columns)
}

with open("artifacts/model_config.json", "w") as f:
    json.dump(config, f, indent=2)

config

import shutil

shutil.make_archive("artifacts", "zip", "artifacts")
files.download("artifacts.zip")

sample_out = X.iloc[:20].copy()
sample_out["actual"] = y.iloc[:20].values
sample_out["predicted"] = y_encoder.inverse_transform(best_model.predict(X_processed.iloc[:20]))
sample_out.to_csv("sample_predictions.csv", index=False)
files.download("sample_predictions.csv")