# -*- coding: utf-8 -*-
"""GarbageDataSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ogOREq3iCUj6F525obbqn5R9IVHjyRf
"""

!pip install -q tensorflow opencv-python-headless seaborn scikit-learn tqdm

import os, glob, shutil, zipfile, random

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.notebook import tqdm

from sklearn.ensemble import IsolationForest
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 100

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

print("TensorFlow:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices("GPU"))

from google.colab import drive
drive.mount('/content/drive')

DRIVE_ZIP_PATH = "/content/drive/My Drive/Datasets/CitizenPulseAI/dataset_256.zip"

LOCAL_DIR = "/content/dataset_256"

if not os.path.exists(LOCAL_DIR):
    print("Extracting dataset from Drive to local Colab disk (faster I/O)...")
    with zipfile.ZipFile(DRIVE_ZIP_PATH, 'r') as zf:
        zf.extractall("/content")
    print("Done.")
else:
    print("Dataset already extracted at", LOCAL_DIR)

TRAIN_DIR = os.path.join(LOCAL_DIR, "train")
VAL_DIR   = os.path.join(LOCAL_DIR, "val")
TEST_DIR  = os.path.join(LOCAL_DIR, "test")

CLASS_NAMES = sorted(os.listdir(TRAIN_DIR))
NUM_CLASSES = len(CLASS_NAMES)
print(f"Classes ({NUM_CLASSES}): {CLASS_NAMES}")

def build_index(split_dir, split_name):
    rows = []
    for cls in CLASS_NAMES:
        cls_dir = os.path.join(split_dir, cls)
        if not os.path.isdir(cls_dir):
            continue
        for fname in os.listdir(cls_dir):
            rows.append({"filepath": os.path.join(cls_dir, fname), "class": cls, "split": split_name})
    return rows

rows = build_index(TRAIN_DIR, "train") + build_index(VAL_DIR, "val") + build_index(TEST_DIR, "test")
df = pd.DataFrame(rows)
print(f"Total images: {len(df)}")
df.head()

fig, ax = plt.subplots(figsize=(12, 6))
sns.countplot(data=df, x="class", hue="split", order=CLASS_NAMES, ax=ax, palette="viridis")
ax.set_title("Class Distribution Across Train / Val / Test Splits", fontsize=14, fontweight="bold")
ax.set_xlabel("Category")
ax.set_ylabel("Number of Images")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/class_distribution.png", dpi=150)
plt.show()

fig, axes = plt.subplots(2, 5, figsize=(18, 8))
for i, cls in enumerate(CLASS_NAMES):
    sample_path = df[df["class"] == cls].sample(1, random_state=SEED)["filepath"].values[0]
    img = cv2.cvtColor(cv2.imread(sample_path), cv2.COLOR_BGR2RGB)
    ax = axes[i // 5, i % 5]
    ax.imshow(img)
    ax.set_title(cls)
    ax.axis("off")
plt.suptitle("Sample Image per Category", fontsize=16, fontweight="bold")
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/sample_grid.png", dpi=150)
plt.show()

def extract_features(filepath):
    img = cv2.imread(filepath)
    if img is None:
        return None
    h, w = img.shape[:2]
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    brightness = gray.mean()
    sharpness = cv2.Laplacian(gray, cv2.CV_64F).var()
    r_mean, g_mean, b_mean = img_rgb[:, :, 0].mean(), img_rgb[:, :, 1].mean(), img_rgb[:, :, 2].mean()
    return {
        "width": w, "height": h, "aspect_ratio": w / h,
        "brightness": brightness, "sharpness": sharpness,
        "r_mean": r_mean, "g_mean": g_mean, "b_mean": b_mean,
    }

N_PER_CLASS = 150
sample_df = df.groupby("class", group_keys=False).apply(
    lambda x: x.sample(min(len(x), N_PER_CLASS), random_state=SEED)
).reset_index(drop=True)

feature_rows = []
for _, row in tqdm(sample_df.iterrows(), total=len(sample_df), desc="Extracting features"):
    feats = extract_features(row["filepath"])
    if feats:
        feats.update({"class": row["class"], "split": row["split"], "filepath": row["filepath"]})
        feature_rows.append(feats)

feat_df = pd.DataFrame(feature_rows)
feat_df.head()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].hist(feat_df["width"], bins=30, color="steelblue", edgecolor="white", alpha=0.85, label="Width")
axes[0].hist(feat_df["height"], bins=30, color="coral", edgecolor="white", alpha=0.6, label="Height")
axes[0].set_title("Image Dimension Distribution")
axes[0].set_xlabel("Pixels"); axes[0].set_ylabel("Frequency"); axes[0].legend()

axes[1].hist(feat_df["aspect_ratio"], bins=30, color="mediumpurple", edgecolor="white")
axes[1].axvline(feat_df["aspect_ratio"].mean(), color="red", linestyle="--",
                 label=f"Mean: {feat_df['aspect_ratio'].mean():.2f}")
axes[1].set_title("Aspect Ratio Distribution")
axes[1].set_xlabel("Width / Height"); axes[1].set_ylabel("Frequency"); axes[1].legend()

plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/dimension_distributions.png", dpi=150)
plt.show()

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.histplot(data=feat_df, x="brightness", hue="class", element="step",
             stat="density", common_norm=False, ax=axes[0], legend=False)
axes[0].set_title("Brightness Distribution by Class")

sns.histplot(feat_df["sharpness"], bins=40, color="teal", ax=axes[1])
axes[1].set_title("Sharpness (Laplacian Variance) Distribution")
axes[1].set_xlabel("Sharpness score")

for ch, color in zip(["r_mean", "g_mean", "b_mean"], ["red", "green", "blue"]):
    sns.kdeplot(feat_df[ch], color=color, label=ch, ax=axes[2])
axes[2].set_title("Mean Color Channel Distributions")
axes[2].legend()

plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/color_brightness_distributions.png", dpi=150)
plt.show()

numeric_cols = ["width", "height", "aspect_ratio", "brightness", "sharpness", "r_mean", "g_mean", "b_mean"]
corr = feat_df[numeric_cols].corr()

plt.figure(figsize=(9, 7))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0, square=True, linewidths=0.5)
plt.title("Correlation Heatmap — Image-Level Features", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/feature_correlation_heatmap.png", dpi=150)
plt.show()

plt.figure(figsize=(10, 7))
sns.scatterplot(data=feat_df, x="brightness", y="sharpness", hue="class",
                 palette="tab10", alpha=0.7, s=40)
plt.title("Brightness vs. Sharpness — Colored by Category", fontsize=14, fontweight="bold")
plt.xlabel("Brightness (mean pixel intensity)")
plt.ylabel("Sharpness (Laplacian variance)")
plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/brightness_vs_sharpness_scatter.png", dpi=150)
plt.show()

iso = IsolationForest(contamination=0.03, random_state=SEED)
feat_df["outlier"] = iso.fit_predict(feat_df[numeric_cols])  # -1 = outlier, 1 = normal
feat_df["outlier"] = feat_df["outlier"].map({1: "Normal", -1: "Outlier"})

print(feat_df["outlier"].value_counts())

plt.figure(figsize=(10, 7))
sns.scatterplot(data=feat_df, x="brightness", y="sharpness", hue="outlier",
                 palette={"Normal": "steelblue", "Outlier": "red"}, alpha=0.7, s=45)
plt.title("Outlier Detection (Isolation Forest) — Brightness vs Sharpness", fontsize=14, fontweight="bold")
plt.xlabel("Brightness"); plt.ylabel("Sharpness")
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/outlier_detection_scatter.png", dpi=150)
plt.show()

n_outliers = (feat_df["outlier"] == "Outlier").sum()
outlier_samples = feat_df[feat_df["outlier"] == "Outlier"].sample(min(8, n_outliers), random_state=SEED)

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
for ax, (_, row) in zip(axes.flatten(), outlier_samples.iterrows()):
    img = cv2.cvtColor(cv2.imread(row["filepath"]), cv2.COLOR_BGR2RGB)
    ax.imshow(img)
    ax.set_title(f"{row['class']}\nbright={row['brightness']:.0f}, sharp={row['sharpness']:.0f}", fontsize=9)
    ax.axis("off")
for ax in axes.flatten()[len(outlier_samples):]:
    ax.axis("off")
plt.suptitle("Sample Detected Outlier Images", fontsize=15, fontweight="bold")
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/outlier_samples.png", dpi=150)
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
sns.boxplot(data=feat_df, x="class", y="brightness", ax=axes[0], palette="Set2")
axes[0].set_title("Brightness by Category (points beyond whiskers = outliers)")
axes[0].tick_params(axis="x", rotation=30)

sns.boxplot(data=feat_df, x="class", y="sharpness", ax=axes[1], palette="Set3")
axes[1].set_title("Sharpness by Category (points beyond whiskers = outliers)")
axes[1].tick_params(axis="x", rotation=30)

plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/boxplots_brightness_sharpness.png", dpi=150)
plt.show()

EMBED_IMG_SIZE = (224, 224)

embed_model = MobileNetV2(input_shape=EMBED_IMG_SIZE + (3,), include_top=False,
                           weights="imagenet", pooling="avg")

def load_and_resize(fp, size=EMBED_IMG_SIZE):
    img = cv2.imread(fp)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, size)
    return img

EMBED_N_PER_CLASS = 60
embed_sample = df.groupby("class", group_keys=False).apply(
    lambda x: x.sample(min(len(x), EMBED_N_PER_CLASS), random_state=SEED)
).reset_index(drop=True)

batch_imgs = np.stack([load_and_resize(fp) for fp in tqdm(embed_sample["filepath"], desc="Loading images")])
batch_imgs = preprocess_input(batch_imgs.astype("float32"))
embeddings = embed_model.predict(batch_imgs, batch_size=64, verbose=1)
print("Embeddings shape:", embeddings.shape)

pca = PCA(n_components=2, random_state=SEED)
pca_result = pca.fit_transform(embeddings)

tsne = TSNE(n_components=2, random_state=SEED, perplexity=30, init="pca")
tsne_result = tsne.fit_transform(embeddings)

embed_sample["pca_x"], embed_sample["pca_y"] = pca_result[:, 0], pca_result[:, 1]
embed_sample["tsne_x"], embed_sample["tsne_y"] = tsne_result[:, 0], tsne_result[:, 1]

fig, axes = plt.subplots(1, 2, figsize=(18, 7))
sns.scatterplot(data=embed_sample, x="pca_x", y="pca_y", hue="class", palette="tab10",
                 ax=axes[0], s=40, alpha=0.8)
axes[0].set_title("PCA of Image Embeddings (MobileNetV2)")

sns.scatterplot(data=embed_sample, x="tsne_x", y="tsne_y", hue="class", palette="tab10",
                 ax=axes[1], s=40, alpha=0.8)
axes[1].set_title("t-SNE of Image Embeddings (MobileNetV2)")

plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/embedding_pca_tsne.png", dpi=150)
plt.show()

import os
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

IMG_SIZE_TRAIN = (224, 224)
BATCH_SIZE = 16   # keep at 16, not 32 — this is what makes 224x224 safe

train_ds = tf.keras.utils.image_dataset_from_directory(
    TRAIN_DIR, image_size=IMG_SIZE_TRAIN, batch_size=BATCH_SIZE,
    label_mode="categorical", seed=SEED)
val_ds = tf.keras.utils.image_dataset_from_directory(
    VAL_DIR, image_size=IMG_SIZE_TRAIN, batch_size=BATCH_SIZE,
    label_mode="categorical", seed=SEED)
test_ds = tf.keras.utils.image_dataset_from_directory(
    TEST_DIR, image_size=IMG_SIZE_TRAIN, batch_size=BATCH_SIZE,
    label_mode="categorical", seed=SEED, shuffle=False)

CLASS_NAMES = train_ds.class_names
print(CLASS_NAMES)

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.1),
])

AUTOTUNE = tf.data.AUTOTUNE

def prep(ds, training=False, cache_path=None):
    ds = ds.map(lambda x, y: (preprocess_input(x), y), num_parallel_calls=AUTOTUNE)
    if training:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y), num_parallel_calls=AUTOTUNE)
    if cache_path:
        ds = ds.cache(cache_path)  # local Colab disk only — NOT Drive
    return ds.prefetch(buffer_size=2)

os.makedirs("/content/cache", exist_ok=True)
train_ds_p = prep(train_ds, training=True, cache_path="/content/cache/train")
val_ds_p   = prep(val_ds, cache_path="/content/cache/val")
test_ds_p  = prep(test_ds, cache_path="/content/cache/test")

base_model = MobileNetV2(input_shape=IMG_SIZE_TRAIN + (3,), include_top=False, weights="imagenet")
base_model.trainable = False

inputs = tf.keras.Input(shape=IMG_SIZE_TRAIN + (3,))
x = base_model(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.2)(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = models.Model(inputs, outputs)
model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
              loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()

MODEL_DIR = "/content/drive/My Drive/Datasets/CitizenPulseAI/models"
os.makedirs(MODEL_DIR, exist_ok=True)

callbacks = [
    EarlyStopping(monitor="val_accuracy", patience=5, restore_best_weights=True),
    ModelCheckpoint(os.path.join(MODEL_DIR, "garbage_classifier_best.keras"),
                     monitor="val_accuracy", save_best_only=True),
    ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, min_lr=1e-6),
]

EPOCHS = 15
history = model.fit(train_ds_p, validation_data=val_ds_p, epochs=EPOCHS, callbacks=callbacks)

base_model.trainable = True
FINE_TUNE_AT = len(base_model.layers) - 40
for layer in base_model.layers[:FINE_TUNE_AT]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
              loss="categorical_crossentropy", metrics=["accuracy"])

FT_EPOCHS = 10
history_ft = model.fit(train_ds_p, validation_data=val_ds_p, epochs=FT_EPOCHS, callbacks=callbacks)

def combine_history(h1, h2, key):
    return h1.history[key] + h2.history[key]

acc = combine_history(history, history_ft, "accuracy")
val_acc = combine_history(history, history_ft, "val_accuracy")
loss = combine_history(history, history_ft, "loss")
val_loss = combine_history(history, history_ft, "val_loss")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].plot(acc, label="Train Accuracy")
axes[0].plot(val_acc, label="Val Accuracy")
axes[0].axvline(len(history.history["accuracy"]), color="gray", linestyle="--", label="Fine-tune start")
best_val_acc = max(val_acc)
axes[0].set_title(f"Accuracy over Epochs (Best Val Accuracy: {best_val_acc * 100:.2f}%)")
axes[0].set_xlabel("Epoch"); axes[0].legend()

axes[1].plot(loss, label="Train Loss")
axes[1].plot(val_loss, label="Val Loss")
axes[1].axvline(len(history.history["loss"]), color="gray", linestyle="--", label="Fine-tune start")
axes[1].set_title("Loss over Epochs"); axes[1].set_xlabel("Epoch"); axes[1].legend()

plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/training_curves.png", dpi=150)
plt.show()

print(f"Best Validation Accuracy: {best_val_acc * 100:.2f}%")

test_loss, test_acc = model.evaluate(test_ds_p)
print("=" * 50)
print(f"FINAL TEST ACCURACY: {test_acc * 100:.2f}%")
print(f"Final Test Loss:     {test_loss:.4f}")
print("=" * 50)

y_true, y_pred = [], []
for images, labels in test_ds_p:
    preds = model.predict(images, verbose=0)
    y_true.extend(np.argmax(labels.numpy(), axis=1))
    y_pred.extend(np.argmax(preds, axis=1))

print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))

cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype("float") / cm.sum(axis=1, keepdims=True)

plt.figure(figsize=(10, 8))
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap="Blues",
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.title(f"Confusion Matrix (Normalized) — Test Accuracy: {test_acc * 100:.2f}%", fontsize=14, fontweight="bold")
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.tight_layout()
plt.savefig("/content/drive/My Drive/Datasets/CitizenPulseAI/confusion_matrix.png", dpi=150)
plt.show()

import pickle

# 1) Keep a standard .keras copy too (recommended for reliable reloads)
FINAL_MODEL_PATH = os.path.join(MODEL_DIR, "garbage_classifier_final.keras")
model.save(FINAL_MODEL_PATH)
print(f"Model saved (.keras) to: {FINAL_MODEL_PATH}")

# 2) Export as .pkl — store architecture (JSON) + weights together so it can
#    actually be reloaded later (a raw pickle of a Keras model object is not reliable).
PKL_MODEL_PATH = os.path.join(MODEL_DIR, "garbage_classifier_final.pkl")

model_package = {
    "architecture": model.to_json(),
    "weights": model.get_weights(),
    "class_names": CLASS_NAMES,
    "img_size": IMG_SIZE_TRAIN,
}

with open(PKL_MODEL_PATH, "wb") as f:
    pickle.dump(model_package, f)

print(f"Model saved (.pkl) to: {PKL_MODEL_PATH}")

# 3) Copy EDA plots to Drive too
PLOTS_DIR = "/content/drive/My Drive/Datasets/CitizenPulseAI/eda_plots"
os.makedirs(PLOTS_DIR, exist_ok=True)
for f in glob.glob("/content/*.png"):
    shutil.copy(f, PLOTS_DIR)
print(f"All plots copied to: {PLOTS_DIR}")

from google.colab import files
files.download(PKL_MODEL_PATH)

# Example: how to reload the model from the .pkl file later
import pickle
from tensorflow.keras.models import model_from_json

with open(PKL_MODEL_PATH, "rb") as f:
    loaded_package = pickle.load(f)

loaded_model = model_from_json(loaded_package["architecture"])
loaded_model.set_weights(loaded_package["weights"])
loaded_class_names = loaded_package["class_names"]

print("Reloaded model from .pkl successfully.")
print("Classes:", loaded_class_names)

def predict_image(filepath, model, class_names, img_size=IMG_SIZE_TRAIN):
    img = cv2.imread(filepath)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img, img_size)
    img_arr = preprocess_input(np.expand_dims(img_resized.astype("float32"), axis=0))
    pred = model.predict(img_arr, verbose=0)[0]
    top_idx = np.argmax(pred)
    plt.imshow(img_resized)
    plt.axis("off")
    plt.title(f"Prediction: {class_names[top_idx]} ({pred[top_idx]*100:.1f}%)")
    plt.show()
    return class_names[top_idx], float(pred[top_idx])

sample_test_img = df[df["split"] == "test"].sample(1, random_state=SEED)["filepath"].values[0]
predict_image(sample_test_img, model, CLASS_NAMES)