import { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    // Navbar
    nav_home: "Home",
    nav_about: "About Us",
    nav_complaint: "Submit Complaint",
    nav_dashboard: "Admin Dashboard",
    nav_subtitle: "Citizen Complaints & Management System",

    // Home Page
    home_hero_badge: "AI-Powered Civic Platform",
    home_hero_title: "Report. Track. Resolve.",
    home_hero_subtitle:
      "Submit citizen complaints for floods, road damage, garbage, power failures, and street lights. Our AI system prioritizes and dispatches issues instantly.",
    home_report_btn: "Report an Issue",
    home_dashboard_btn: "View Dashboard",
    home_categories_title: "Issue Categories",
    home_how_title: "How It Works",
    home_step1_title: "Submit Your Report",
    home_step1_desc: "Fill in the complaint form with details and optional GPS location.",
    home_step2_title: "AI Analysis",
    home_step2_desc: "Our AI model assesses severity and prioritizes the issue automatically.",
    home_step3_title: "Field Dispatch",
    home_step3_desc: "Relevant municipal teams are notified and dispatched to resolve the issue.",
    home_stats_complaints: "Complaints Handled",
    home_stats_response: "Avg Response Time",
    home_stats_resolved: "Issues Resolved",
    home_stats_districts: "Districts Covered",

    // Category labels
    cat_flood: "Flood & Drainage",
    cat_road: "Road Damage",
    cat_garbage: "Garbage & Waste",
    cat_power: "Power Failure",
    cat_light: "Street Lights",

    // Complaint Form
    form_title: "Submit a Complaint",
    form_subtitle: "Report a civic issue in your area",
    form_category_label: "Issue Category",
    form_name_label: "Full Name",
    form_name_placeholder: "e.g. Kamal Perera",
    form_phone_label: "Phone Number",
    form_phone_placeholder: "e.g. 077 123 4567",
    form_description_label: "Describe the Issue",
    form_description_placeholder: "Provide as much detail as possible about the issue...",
    form_location_label: "Location",
    form_location_btn: "Auto-Detect Location (GPS)",
    form_location_detecting: "Detecting location...",
    form_district_label: "District",
    form_district_placeholder: "e.g. Colombo",
    form_city_label: "City / Town",
    form_city_placeholder: "e.g. Kaduwela",
    form_area_label: "Area / Street",
    form_area_placeholder: "e.g. Main Street, Ward 3",
    form_photo_label: "Upload Photo (Optional)",
    form_photo_hint: "Supported: JPG, PNG, WEBP (max 10MB)",
    form_submit_btn: "Submit Complaint",
    form_submitting: "Submitting...",
    form_success_title: "Complaint Submitted!",
    form_success_tracking: "Tracking ID",
    form_success_msg: "Your complaint has been registered and our team has been notified.",
    form_success_redirect: "Redirecting to Home Page in",
    form_success_redirect_s: "seconds...",
    form_success_go_home: "Go to Home Page Now →",
    form_location_optional: "Location is optional — you can type it manually below.",

    // Dashboard
    dash_title: "Municipal Admin Dashboard",
    dash_subtitle: "Real-time triage and field dispatch overview for citizen complaints.",
    dash_total: "TOTAL COMPLAINTS",
    dash_critical: "CRITICAL / HIGH RISK",
    dash_active: "Active",
    dash_cases: "Cases",
    dash_breakdown: "Issue Breakdown by Category",
    dash_logs: "Recent Incident Logs",
    dash_showing: "Showing",
    dash_reports: "report(s) sorted by submission time",
    dash_clear_filter: "Clear Filter (Show All)",
    dash_no_data: "No complaints found for this category.",
    dash_col_id: "TRACKING ID",
    dash_col_citizen: "CITIZEN",
    dash_col_category: "CATEGORY",
    dash_col_location: "LOCATION",
    dash_col_severity: "SEVERITY",
    dash_col_status: "STATUS",
    dash_col_submitted: "SUBMITTED",
    dash_filter_active: "Filter Active ✓",
    dash_click_filter: "Click to filter",
    dash_pending_ai: "⏳ Pending AI",

    // About page
    about_eyebrow: "Civic Intelligence Platform",
    about_hero_title_1: "See the problem.",
    about_hero_title_2: "Get it to the right desk.",
    about_lede: "CivicPulse AI turns a photo and a pin on the map into a structured case file — categorized, located and routed to the department that can actually act on it.",
    about_cta_report: "Report an issue",
    about_cta_dashboard: "View dashboard",
    about_intro_label: "About CivicPulse AI",
    about_intro_heading_1: "Built for the space between",
    about_intro_heading_2: "a citizen and city hall.",
    about_intro_p1: "CivicPulse AI is a civic-reporting platform that replaces scattered phone calls and hallway complaints with a single, searchable record. One photo, one location, one case number per issue.",
    about_intro_p2: "Whether it's a pothole on the school run or a transformer that's been sparking for a week, every report follows the same path: submitted, located, reviewed, and handed to the office responsible for fixing it.",
    about_what_it_does: "What it does",
    about_features_title: "A structured way to report and respond.",
    about_features_desc: "Four parts working together — reporting, triage, mapping and dashboards — so a filed report doesn't just disappear.",
    about_issue_types: "Issue types",
    about_categories_title: "One form for every kind of problem.",
    about_categories_desc: "Each category asks the questions relevant to that issue, so the department on the other end gets what it actually needs — not a generic complaint box.",
    about_mission_label: "Why this exists",
    about_mission_title: "Every report deserves a paper trail.",
    about_mission_desc: "Most civic complaints disappear into inboxes and phone logs with no way to follow up later. CivicPulse AI gives every report a case number, a location and a status, so citizens can see what happened to what they filed, and departments have a record of how they responded.",
    about_final_label: "Got something to report?",
    about_final_title: "Start with what you see.",
    about_final_desc: "A pothole, a broken light, a garbage pile that's been there for weeks — if it affects your street, it belongs in the system.",
  },
  si: {
    // Navbar
    nav_home: "මුල් පිටුව",
    nav_about: "අපි ගැන",
    nav_complaint: "පැමිණිල්ල ඉදිරිපත් කරන්න",
    nav_dashboard: "පරිපාලක උපකරණ පුවරුව",
    nav_subtitle: "පුරවැසි පැමිණිලි සහ කළමනාකරණ පද්ධතිය",

    // Home Page
    home_hero_badge: "AI-පාදක සිවිල් වේදිකාව",
    home_hero_title: "වාර්තා කරන්න. ගමන් කරන්න. විසඳන්න.",
    home_hero_subtitle:
      "ගංවතුර, මාර්ග හානි, කසළ, විදුලි බිඳ වැටීම් සහ වීදි ලාම්පු සඳහා පැමිණිලි ඉදිරිපත් කරන්න. අපගේ AI පද්ධතිය ගැටළු ප්‍රමුඛතා ලෙස සලකා ක්ෂණිකව යොමු කරයි.",
    home_report_btn: "ගැටළුවක් වාර්තා කරන්න",
    home_dashboard_btn: "උපකරණ පුවරුව බලන්න",
    home_categories_title: "ගැටළු වර්ග",
    home_how_title: "ක්‍රියා කරන ආකාරය",
    home_step1_title: "ඔබේ වාර්තාව ඉදිරිපත් කරන්න",
    home_step1_desc: "GPS ස්ථානය සහ තොරතුරු සමඟ පැමිණිලි පෝරමය පුරවන්න.",
    home_step2_title: "AI විශ්ලේෂණය",
    home_step2_desc: "අපගේ AI ආකෘතිය ස්වයංක්‍රීයව බරපතලකම ඇගයීම් කරයි.",
    home_step3_title: "ක්ෂේත්‍ර යොමු කිරීම",
    home_step3_desc: "අදාළ නාගරික කණ්ඩායම් දැනුම් දී ගැටළුව විසඳීමට යොමු කරනු ලැබේ.",
    home_stats_complaints: "හැසිරවූ පැමිණිලි",
    home_stats_response: "සාම. ප්‍රතිචාර කාලය",
    home_stats_resolved: "විසඳූ ගැටළු",
    home_stats_districts: "ආවරණය වූ දිස්ත්‍රික්ක",

    // Category labels
    cat_flood: "ගංවතුර සහ ජල බැස්සීම",
    cat_road: "මාර්ග හානි",
    cat_garbage: "කසළ සහ අපද්‍රව්‍ය",
    cat_power: "විදුලි බිඳ වැටීම",
    cat_light: "වීදි ලාම්පු",

    // Complaint Form
    form_title: "පැමිණිල්ල ඉදිරිපත් කරන්න",
    form_subtitle: "ඔබේ ප්‍රදේශයේ ගැටළුවක් වාර්තා කරන්න",
    form_category_label: "ගැටළු වර්ගය",
    form_name_label: "සම්පූර්ණ නම",
    form_name_placeholder: "උදා: කමල් පෙරේරා",
    form_phone_label: "දුරකථන අංකය",
    form_phone_placeholder: "උදා: 077 123 4567",
    form_description_label: "ගැටළුව විස්තර කරන්න",
    form_description_placeholder: "ගැටළුව පිළිබඳ හැකිතාක් විස්තර සඳහන් කරන්න...",
    form_location_label: "ස්ථානය",
    form_location_btn: "ස්වයං-GPS ස්ථාන හඳුනාගැනීම",
    form_location_detecting: "ස්ථානය හඳුනාගනිමින්...",
    form_district_label: "දිස්ත්‍රික්කය",
    form_district_placeholder: "උදා: කොළඹ",
    form_city_label: "නගරය",
    form_city_placeholder: "උදා: කදුවෙල",
    form_area_label: "ප්‍රදේශය / වීදිය",
    form_area_placeholder: "උදා: ප්‍රධාන වීදිය, 3 වැනි නාය",
    form_photo_label: "ඡායාරූපය උඩුගත කරන්න (අමතරව)",
    form_photo_hint: "JPG, PNG, WEBP සඳහා සහාය (උපරිම 10MB)",
    form_submit_btn: "පැමිණිල්ල ඉදිරිපත් කරන්න",
    form_submitting: "ඉදිරිපත් කරමින්...",
    form_success_title: "පැමිණිල්ල ඉදිරිපත් කරන ලදී!",
    form_success_tracking: "නිරීක්ෂණ ID",
    form_success_msg: "ඔබේ පැමිණිල්ල ලියාපදිංචි කර අපගේ කණ්ඩායමට දැනුම් දී ඇත.",
    form_success_redirect: "මුල් පිටුවට යොමු කෙරේ",
    form_success_redirect_s: "තත්පරවලින්...",
    form_success_go_home: "දැන් මුල් පිටුවට යන්න →",
    form_location_optional: "ස්ථානය අනිවාර්ය නොවේ — ඔබට පහතින් අතින් ටයිප් කළ හැකිය.",

    // Dashboard
    dash_title: "නාගරික පරිපාලක උපකරණ පුවරුව",
    dash_subtitle: "පුරවැසි පැමිණිලි සඳහා තාත්කාලික ත්‍රිආජ් සහ ක්ෂේත්‍ර යොමු දළ විශ්ලේෂණය.",
    dash_total: "මුළු පැමිණිලි",
    dash_critical: "තීරණාත්මක / ඉහළ අවදානම",
    dash_active: "සක්‍රිය",
    dash_cases: "නඩු",
    dash_breakdown: "වර්ගය අනුව ගැටළු බෙදීම",
    dash_logs: "මෑත සිදුවීම් ලොග",
    dash_showing: "පෙන්වීම",
    dash_reports: "ඉදිරිපත් කිරීමේ වේලාව අනුව වාර්තා",
    dash_clear_filter: "පෙරහන ඉවත් කරන්න",
    dash_no_data: "මෙම වර්ගය සඳහා පැමිණිලි නොමැත.",
    dash_col_id: "නිරීක්ෂණ ID",
    dash_col_citizen: "පුරවැසියා",
    dash_col_category: "වර්ගය",
    dash_col_location: "ස්ථානය",
    dash_col_severity: "බරපතලකම",
    dash_col_status: "තත්ත්වය",
    dash_col_submitted: "ඉදිරිපත් කළේ",
    dash_filter_active: "පෙරහන සක්‍රිය ✓",
    dash_click_filter: "පෙරහනට ක්ලික් කරන්න",
    dash_pending_ai: "⏳ AI විශ්ලේෂණය",

    // About page
    about_eyebrow: "සිවිල් බුද්ධි වේදිකාව",
    about_hero_title_1: "ගැටළුව දැක ගන්න.",
    about_hero_title_2: "එය නිවැරදි දෙපාර්තමේන්තුව වෙත යොමු කරන්න.",
    about_lede: "CivicPulse AI මගින් ඡායාරූපයක් සහ සිතියම් මත ලකුණක් එක්කර ව්‍යුහගත සිද්ධි ගොනු බවට පත් කරයි — වර්ගීකරණය කර, ස්ථානය තිරසාරව තබා සැබෑවට ක්‍රියා කළ හැකි දෙපාර්තමේන්තුවට යොමු කරයි.",
    about_cta_report: "ගැටළුවක් වාර්තා කරන්න",
    about_cta_dashboard: "උපකරණ පුවරුව බලන්න",
    about_intro_label: "CivicPulse AI ගැන",
    about_intro_heading_1: "පුරවැසියා සහ නගර සභාව",
    about_intro_heading_2: " අතර අවකාශයට නිර්මාණය කර ඇත.",
    about_intro_p1: "CivicPulse AI යනු පැතිරුම් දුරකථන ඇමතුම් සහ මංමුලා සංකල්ප මගින් ව්‍යාප්තව ඇති පැමිණිලි ඩිජිටල්ව පාලනය කරන සිවිල් වාර්තා වේදිකාවකි. එක් ඡායාරූපයක්, එක් ස්ථානයක්, එක් නඩු අංකයක් එකම ගැටළුව සඳහා.",
    about_intro_p2: "පාසල් මාර්ගයේ ගිලීම් ගැටළුවක් හෝ සතියක් තිස්සේ සම්ප්‍රේෂණය වන ට්‍රාන්ස්ෆෝමරයක් වුවද, සෑම වාර්තාවක්ම එකම මාර්ගයෙන් ගමන් කරයි: ඉදිරිපත් කිරීම, ස්ථානය සකස් කිරීම, සමාලෝචනය සහ එය විසඳීමට වගකියන කාර්යාලයට ලබා දීම.",
    about_what_it_does: "එය කරන්නේ කුමක්ද",
    about_features_title: "වාර්තා කිරීමට සහ ප්‍රතිචාර දීමට ව්‍යුහගත ආකාරය.",
    about_features_desc: "වාර්තා කිරීම, තක්සේරු කිරීම, සිතියම්කරණය සහ උපකරණ පුවරු එකට ක්‍රියා කරයි, එමඟින් වාර්තා වරක් ලියා ඇතුව නොනැවතී යයි.",
    about_issue_types: "ගැටළු වර්ග",
    about_categories_title: "සෑම ගැටළුවක් සඳහාම එක් පෝරමයක්.",
    about_categories_desc: "සෑම වර්ගයක්ම එහි අදාළ ප්‍රශ්න ගෙන්වයි, එමඟින් අදාළ දෙපාර්තමේන්තුවට අවශ්‍ය දත්ත ලැබෙන අතර සාමාන්‍ය පැමිණිල්ලකින් නොව වෙනස් වාර්තාවක් ලැබේ.",
    about_mission_label: "මෙය ඇති වන්නේ ඇයි",
    about_mission_title: "සෑම වාර්තාවක්ම ලිපිගොනුවක් අත්‍යාවශ්‍ය වේ.",
    about_mission_desc: "බොහෝ සිවිල් පැමිණිලි ඊමේල් හා දුරකථන ලොගවල අතුරුදහන් විය හැකි අතර පසුව අනුගමනය කළ නොහැක. CivicPulse AI සෑම වාර්තාවක්ම නඩු අංකයක්, ස්ථානයක් සහ තත්ත්වයක් ලබා දේ, එමඟින් පුරවැසියන්ට තම වාර්තාව කුමක් කළේදැයි දැනගැනීමට සහ දෙපාර්තමේන්තුවට ප්‍රතිචාරය ලේඛනගත කිරීමට හැකියාව ලැබේ.",
    about_final_label: "වාර්තා කිරීමට දෙයක් තිබේද?",
    about_final_title: "ඔබ දකින දේවලින් පටන් ගන්න.",
    about_final_desc: "ගිල්වෙමින් ඇති මාර්ග, කැඩුණු ලාම්පු, හෝ සති ගණනාවක සිට ඇති කසළ ගොඩක් — ඔබේ වීදියේ බලපාන ඕනෑම දෙයක් පද්ධතියට ඇතුළත් විය යුතුය.",
  },
  ta: {
    // Navbar
    nav_home: "முகப்பு",
    nav_about: "எங்களைப் பற்றி",
    nav_complaint: "புகார் சமர்ப்பிக்கவும்",
    nav_dashboard: "நிர்வாகக் குழு",
    nav_subtitle: "குடிமக்கள் புகார் மற்றும் மேலாண்மை அமைப்பு",

    // Home Page
    home_hero_badge: "AI-ஆதரவு சிவில் தளம்",
    home_hero_title: "அறிக்கை. கண்காணிக்கவும். தீர்க்கவும்.",
    home_hero_subtitle:
      "வெள்ளம், சாலை சேதம், குப்பை, மின்சாரம் நிறுத்தம் மற்றும் தெரு விளக்குகள் குறித்த புகார்களை சமர்ப்பிக்கவும். எங்கள் AI அமைப்பு தானாகவே சிக்கல்களை முன்னுரிமைப்படுத்தி தொடர்புடைய துறைக்கு அனுப்பும்.",
    home_report_btn: "ஒரு சிக்கலை புகாரளிக்கவும்",
    home_dashboard_btn: "நிர்வாகக் குழுவைக் காண்க",
    home_categories_title: "சிக்கல் வகைகள்",
    home_how_title: "இது எவ்வாறு செயல்படுகிறது",
    home_step1_title: "உங்கள் அறிக்கையை சமர்ப்பிக்கவும்",
    home_step1_desc: "புகார் படிவத்தில் இருப்பிடம் மற்றும் விவரங்களுடன் நிரப்பவும்.",
    home_step2_title: "AI பகுப்பாய்வு",
    home_step2_desc: "எங்கள் AI மாதிரி தானாகவே தீவிரத்தை மதிப்பிடுகிறது.",
    home_step3_title: "களப் பணி",
    home_step3_desc: "தொடர்புடைய மாநகராட்சி குழுக்களுக்கு அறிவிக்கப்பட்டு பிரச்சனை தீர்க்கப்படும்.",
    home_stats_complaints: "கையாளப்பட்ட புகார்கள்",
    home_stats_response: "சராசரி பதிலளிப்பு நேரம்",
    home_stats_resolved: "தீர்க்கப்பட்ட சிக்கல்கள்",
    home_stats_districts: "உள்ளடக்கப்பட்ட மாவட்டங்கள்",

    // Category labels
    cat_flood: "வெள்ளம் மற்றும் வடிகால்",
    cat_road: "சாலை சேதம்",
    cat_garbage: "குப்பை மற்றும் கழிவு",
    cat_power: "மின்சாரம் நிறுத்தம்",
    cat_light: "தெரு விளக்குகள்",

    // Complaint Form
    form_title: "ஒரு புகாரை சமர்ப்பிக்கவும்",
    form_subtitle: "உங்கள் பகுதியில் ஒரு சிவில் சிக்கலை புகாரளிக்கவும்",
    form_category_label: "சிக்கல் வகை",
    form_name_label: "முழு பெயர்",
    form_name_placeholder: "எ.கா. கமல் பெரேரா",
    form_phone_label: "தொலைபேசி எண்",
    form_phone_placeholder: "எ.கா. 077 123 4567",
    form_description_label: "சிக்கலை விவரிக்கவும்",
    form_description_placeholder: "சிக்கலைப் பற்றிய முடிந்தவரை அதிகமான விவரங்களை வழங்கவும்...",
    form_location_label: "இடம்",
    form_location_btn: "தானியங்கி GPS இருப்பிட கண்டறிதல்",
    form_location_detecting: "இருப்பிடத்தை கண்டறிகிறது...",
    form_district_label: "மாவட்டம்",
    form_district_placeholder: "எ.கா. கொழும்பு",
    form_city_label: "நகரம் / ஊர்",
    form_city_placeholder: "எ.கா. கடுவெல",
    form_area_label: "பகுதி / தெரு",
    form_area_placeholder: "எ.கா. பிரதான வீதி, வார்டு 3",
    form_photo_label: "புகைப்படத்தை பதிவேற்றவும் (விருப்பத்தேர்வு)",
    form_photo_hint: "ஆதரிக்கப்படும்: JPG, PNG, WEBP (அதிகபட்சம் 10MB)",
    form_submit_btn: "புகாரை சமர்ப்பிக்கவும்",
    form_submitting: "சமர்ப்பிக்கிறது...",
    form_success_title: "புகார் சமர்ப்பிக்கப்பட்டது!",
    form_success_tracking: "கண்காணிப்பு ID",
    form_success_msg: "உங்கள் புகார் பதிவு செய்யப்பட்டுள்ளது மற்றும் எங்கள் குழுவுக்கு அறிவிக்கப்பட்டுள்ளது.",
    form_success_redirect: "முகப்பு பக்கத்திற்கு செல்கிறது",
    form_success_redirect_s: "வினாடிகளில்...",
    form_success_go_home: "இப்போது முகப்பு பக்கத்திற்குச் செல்லவும் →",
    form_location_optional: "இடம் விருப்பத்தேர்வு — நீங்கள் கீழே கைமுறையாக தட்டச்சு செய்யலாம்.",

    // Dashboard
    dash_title: "மாநகராட்சி நிர்வாகக் குழு",
    dash_subtitle: "குடிமக்கள் புகார்களுக்கான நிகழ்நேர ட்ரியேஜ் மற்றும் களப்பணி கண்ணோட்டம்.",
    dash_total: "மொத்த புகார்கள்",
    dash_critical: "மிக முக்கியமான / அதிக ஆபத்து",
    dash_active: "செயலில் உள்ள",
    dash_cases: "வழக்குகள்",
    dash_breakdown: "வகைப்படி சிக்கல் முறிவு",
    dash_logs: "சமீபத்திய நிகழ்வு பதிவுகள்",
    dash_showing: "காட்டுகிறது",
    dash_reports: "சமர்ப்பிக்கும் நேரத்தின்படி வரிசைப்படுத்தப்பட்ட அறிக்கை(கள்)",
    dash_clear_filter: "வடிகட்டியை அகற்று",
    dash_no_data: "இந்த வகைக்கு எந்த புகார்களும் காணப்படவில்லை.",
    dash_col_id: "கண்காணிப்பு ID",
    dash_col_citizen: "குடிமகன்",
    dash_col_category: "வகை",
    dash_col_location: "இடம்",
    dash_col_severity: "தீவிரம்",
    dash_col_status: "நிலை",
    dash_col_submitted: "சமர்ப்பிக்கப்பட்டது",
    dash_filter_active: "வடிகட்டி செயலில் உள்ளது ✓",
    dash_click_filter: "வடிகட்ட கிளிக் செய்க",
    dash_pending_ai: "⏳ AI நிலுவையில் உள்ளது",

    // About page
    about_eyebrow: "சிவில் புலனாய்வு தளம்",
    about_hero_title_1: "சிக்கலைப் பாருங்கள்.",
    about_hero_title_2: "சரியான துறைக்கு கொண்டு செல்லுங்கள்.",
    about_lede: "CivicPulse AI ஒரு புகைப்படம் மற்றும் வரைபடத்தில் ஒரு புள்ளியை கட்டமைக்கப்பட்ட வழக்கு கோப்பாக மாற்றுகிறது — வகைப்படுத்தப்பட்டு, கண்டுபிடிக்கப்பட்டு, உண்மையில் செயல்படக்கூடிய துறைக்கு அனுப்பப்படுகிறது.",
    about_cta_report: "ஒரு சிக்கலை புகாரளிக்கவும்",
    about_cta_dashboard: "நிர்வாகக் குழுவைக் காண்க",
    about_intro_label: "CivicPulse AI பற்றி",
    about_intro_heading_1: "ஒரு குடிமகனுக்கும் நகர மன்றத்திற்கும்",
    about_intro_heading_2: " இடையிலான இடைவெளிக்காக உருவாக்கப்பட்டது.",
    about_intro_p1: "CivicPulse AI என்பது ஒரு சிவில்-அறிக்கை தளமாகும், இது சிதறிய தொலைபேசி அழைப்புகள் மற்றும் புகார்களை தேடக்கூடிய ஒரே பதிவாக மாற்றுகிறது. ஒரு புகைப்படம், ஒரு இடம், ஒரு சிக்கலுக்கு ஒரு வழக்கு எண்.",
    about_intro_p2: "இது பள்ளி சாலையில் ஒரு குழியாக இருந்தாலும் சரி, ஒரு வாரமாக ஸ்பார்க் செய்து கொண்டிருக்கும் மின்மாற்றியாக இருந்தாலும் சரி, ஒவ்வொரு அறிக்கையும் ஒரே பாதையைப் பின்பற்றுகிறது: சமர்ப்பிக்கப்பட்டது, அமைவிடம் கண்டறியப்பட்டது, மதிப்பாய்வு செய்யப்பட்டு, அதைச் சரிசெய்வதற்குப் பொறுப்பான அலுவலகத்திடம் ஒப்படைக்கப்படுகிறது.",
    about_what_it_does: "அது என்ன செய்கிறது",
    about_features_title: "புகாரளிக்க மற்றும் பதிலளிக்க கட்டமைக்கப்பட்ட வழி.",
    about_features_desc: "நான்கு பகுதிகள் ஒன்றாக செயல்படுகின்றன — அறிக்கை, ட்ரியேஜ், வரைபடமாக்கல் மற்றும் டாஷ்போர்டுகள் — எனவே பதிவு செய்யப்பட்ட அறிக்கை மறைந்துவிடாது.",
    about_issue_types: "சிக்கல் வகைகள்",
    about_categories_title: "ஒவ்வொரு வகையான பிரச்சனைக்கும் ஒரு படிவம்.",
    about_categories_desc: "ஒவ்வொரு வகையும் அந்த சிக்கலுக்குத் தொடர்புடைய கேள்விகளைக் கேட்கிறது, எனவே மறுமுனையில் உள்ள துறைக்குத் தேவையானது கிடைக்கும் — பொதுவான புகார் பெட்டி அல்ல.",
    about_mission_label: "இது ஏன் உள்ளது",
    about_mission_title: "ஒவ்வொரு அறிக்கையும் ஒரு காகிதப் பாதையைப் பெறத் தகுதியானது.",
    about_mission_desc: "பெரும்பாலான சிவில் புகார்கள் இன்பாக்ஸ்கள் மற்றும் தொலைபேசிப் பதிவுகளில் காணாமல் போகின்றன, பின்னர் பின்தொடர வழியில்லை. CivicPulse AI ஒவ்வொரு அறிக்கைக்கும் ஒரு வழக்கு எண், இருப்பிடம் மற்றும் நிலையை வழங்குகிறது, எனவே குடிமக்கள் அவர்கள் தாக்கல் செய்ததை என்ன நடந்தது என்பதைப் பார்க்க முடியும், மேலும் துறைகள் அவர்கள் எவ்வாறு பதிலளித்தார்கள் என்பதற்கான பதிவைக் கொண்டுள்ளன.",
    about_final_label: "புகாரளிக்க ஏதாவது உள்ளதா?",
    about_final_title: "நீங்கள் பார்ப்பதைக் கொண்டு தொடங்குங்கள்.",
    about_final_desc: "ஒரு குழி, உடைந்த விளக்கு, வாரக் கணக்கில் இருக்கும் குப்பைக் குவியல் — அது உங்கள் தெருவைப் பாதித்தால், அது கணினியில் இருக்க வேண்டும்.",
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("cp_lang") || "en";
  });

  const switchLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem("cp_lang", newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
